#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

WORKER_INSTANCE="${WORKER_INSTANCE:-alfab}"
WORKER_USER="${WORKER_USER:-symphony}"

WORKFLOW_REPO_URL="${WORKFLOW_REPO_URL:-https://github.com/motis-group/alfab.git}"
WORKFLOW_REPO_BRANCH="${WORKFLOW_REPO_BRANCH:-main}"
SYMPHONY_PROJECTS_ROOT="${SYMPHONY_PROJECTS_ROOT:-/opt/symphony-projects}"
WORKFLOW_REPO_DIR="${WORKFLOW_REPO_DIR:-${SYMPHONY_PROJECTS_ROOT}/${WORKER_INSTANCE}/repo}"
WORKFLOW_FILE_RELATIVE_PATH="${WORKFLOW_FILE_RELATIVE_PATH:-WORKFLOW.md}"
WORKSPACE_ROOT="${WORKSPACE_ROOT:-/home/${WORKER_USER}/code/symphony-workspaces/${WORKER_INSTANCE}}"
SYMPHONY_LOGS_ROOT="${SYMPHONY_LOGS_ROOT:-/var/lib/symphony/logs/${WORKER_INSTANCE}}"

export WORKER_USER
export WORKFLOW_REPO_URL
export WORKFLOW_REPO_BRANCH
export SYMPHONY_PROJECTS_ROOT
export WORKFLOW_REPO_DIR
export WORKFLOW_FILE_RELATIVE_PATH
export WORKER_INSTANCE
export WORKSPACE_ROOT
export SYMPHONY_LOGS_ROOT

bash "${SCRIPT_DIR}/bootstrap-symphony-worker-host.sh"
bash "${SCRIPT_DIR}/register-symphony-worker-project.sh"
