name: Deploy Costing App

on:
  push:
    branches:
      - main
    paths:
      - 'web-app/**'
      - '.github/workflows/**'
      - 'scripts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      REMOTE_PATH: /var/www/alfab
      APP_PATH: web-app
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'web-app/package.json'

      - name: Install dependencies
        working-directory: web-app
        run: npm install

      - name: Build NextJS app
        working-directory: web-app
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          chmod +x scripts/load-env.sh scripts/deploy.sh
          source scripts/load-env.sh && load_env && ./scripts/deploy.sh
