- name: Deploy to server
        env:
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
          REMOTE_PATH: /var/www/alfab
          APP_PATH: web-app
        run: |
          # First fix the hostname issue
          sshpass -p $REMOTE_PASSWORD ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            if ! grep -q 'alfab-1' /etc/hosts; then
              echo '127.0.0.1 alfab-1' | sudo tee -a /etc/hosts
            fi
          "

          # Stop existing service and clear directory
          sshpass -p $REMOTE_PASSWORD ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo systemctl stop nextjs || true
            sudo rm -rf $REMOTE_PATH/*
            mkdir -p $REMOTE_PATH
          "

          # Copy built files to server
          sshpass -p $REMOTE_PASSWORD scp -o StrictHostKeyChecking=no -r \
            $APP_PATH/.next \
            $APP_PATH/package*.json \
            $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/

          # Update service file
          SYSTEMD_SERVICE="[Unit]
          Description=Next.js application
          After=network.target

          [Service]
          Type=simple
          User=www-data
          WorkingDirectory=$REMOTE_PATH
          ExecStart=/usr/bin/npm start
          Restart=on-failure
          Environment=NODE_ENV=production
          Environment=PORT=10000

          [Install]
          WantedBy=multi-user.target"

          echo "$SYSTEMD_SERVICE" | sshpass -p $REMOTE_PASSWORD ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo tee /etc/systemd/system/nextjs.service"

          # Update nginx configuration
          NGINX_CONFIG="server {
              listen 80;
              server_name alfabvic.com.au;
              
              location / {
                  proxy_pass http://localhost:10000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade \$http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host \$host;
                  proxy_cache_bypass \$http_upgrade;
              }

              location /_next/static/ {
                  alias $REMOTE_PATH/.next/static/;
                  expires 365d;
                  access_log off;
              }
          }"

          echo "$NGINX_CONFIG" | sshpass -p $REMOTE_PASSWORD ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "sudo tee /etc/nginx/sites-available/nextjs"

          # Set permissions and restart services
          sshpass -p $REMOTE_PASSWORD ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo chown -R www-data:www-data $REMOTE_PATH
            cd $REMOTE_PATH
            npm install --production --no-audit
            sudo systemctl daemon-reload
            sudo systemctl enable nextjs
            sudo systemctl restart nextjs
            sudo ln -sf /etc/nginx/sites-available/nextjs /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl restart nginx
          "

          echo "Deployment completed successfully!"